# Generated by Django 5.2.8 on 2026-06-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStructure',
            fields=[
                ('Project_id', models.AutoField(primary_key=True, serialize=False)),
                ('Icon', models.TextField(default='📁')),
                ('Name', models.CharField(max_length=150)),
            ],
        ),
    ]
