# Generated by Django 5.2.8 on 2026-06-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstructure',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
